name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: node_modules
          key: ${{ runner.os }}-go-dep-${{ hashFiles('**/yarn.lock') }}
      - name: dependencies
        run: yarn install
      - name: build
        run: |
          yarn build
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: argoproj/argoproj.github.io
          publish_branch: master
          publish_dir: ./public
